[Database]
Driver=MySQL ODBC 9.6 Unicode Driver
Server=ujumia-mysql.c7i0yk84idw5.ap-southeast-2.rds.amazonaws.com
Port=3306
Database=ujumia_db
UID=root
PWD=dnwnaldkelql!

[Server]
#IP=127.0.0.1
IP = 172.30.1.97
Port=7777
WorkerThreads=5